### PR TITLE
Optimize docker image

### PR DESCRIPTION
**Pull request by Tchoupinax**
Hello ! :)

Your project promises to be interesting so that's a first PR to help you.
I think you can use alpine instead of ubuntu to reduce the image. I do not see what can cause an issue with that.

While I read the Dockerfile, I did not understand while you made the following things:
- create a src folder and write a main.rs inside
- create a main.rs file and build

You source already has a main.rs. It is test for testing?

Have a nice day!

### CODE REVIEW

**Comment by afitzek** [comment]
Hi @Tchoupinax that was a quick first PR thank you! :)

The approach with 
- create a src folder and write a main.rs inside
- create a main.rs file and build

allows for quicker builds, because in the first build it will compile and cache (using docker layer caching) the dependencies which don't have to be recompiled unless the Cargo files change.

Unfortunately we can't use alpine as runtime image because it doesn't include libgcc, but operates with muslc:

```
ldd /metrics
        /lib64/ld-linux-x86-64.so.2 (0x7fec8eb03000)
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /metrics)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fec8eb03000)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fec8eb03000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fec8eb03000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fec8eb03000)
``` 

My first version used distroless, which was smaller but provides a libgcc but it was missing a shell, which is currently needed in the entry.sh script. I'm thinking about implementing the follow operation of tail in rust directly, which would allow us to not require a shell and than we could switch the runtime stage to distroless.

**Comment by Tchoupinax** [comment]
Thank you for your interesting reflexions.

I understand your first point. It means, you can't install the dependancies without having a src folder and a main file? For exemple, Node.js if you know it, you can install dependancies only with your `package.json` and your `package-lock.json`. I understand here you have, in addition, have a `src/main.rs` to be able to do this work. Right?

```
COPY ["./metrics/Cargo.toml", "./metrics/Cargo.lock", "./"]
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release

COPY ["./metrics/src", "./src"]
RUN touch src/main.rs
```

So now I understand the first 3 lines, but the `touch src/main.rs` stays a mystery for me. You source code contains a `main.rs`, right ? ^^'

I understand and see you have already thought about the problematic. Could alpine image work with installing dependancies like `libgcc`. Even with this, it could be lighter.
Using distroless will be without doubt the solution when the dependancy of the shell will not exist anymore!

**Comment by afitzek** [comment]
Yes exactly it is basically the same pattern as with node and the `package.json` and `package-lock.json`, but with cargo there is no `npm ci`, one has to create an "empty" main file and compile the project. The touch is required to make sure that we invalidate the compilers cache of the actual user code for build. Yes my source contains a `main.rs`.

Ah sorry I didn't mean the `libgcc` but `glibc`, afaik there is no such package, because not using glibc but muslc is one of the defining properties of alpine. Muslc allows for fully static linking. There might be a way to build the rust binary for muslc, but I have always had problems with that.

Yes I'm not really happy with the image size and using `ubuntu` as runtime stage. :sweat_smile:

**Comment by afitzek** [comment]
@Tchoupinax You nerd snipped me :laughing: 
I created a PR (https://github.com/afitzek/hasura-metric-adapter/pull/2 ) to move to distroless by implementing a naive implementation of the follow option of tail therefore removing the need for a shell in the runtime stage.

Let me know what you think. :smile:

**Comment by Tchoupinax** [comment]
Hey @afitzek!

Happy to motivate you ;)
I will check this. Happy to learn a lot a things about rust.

Does the #2 closes this one so?

**Comment by afitzek** [comment]
Hi @Tchoupinax, 
I just merged #2 because I wanted to deploy it to k8s cluster, but still happy to get your feedback on it.

Yeah I think with #2 we don't need this one anymore.

**Comment by afitzek** [comment]
I'm closing this, since I think its not relevant anymore. We migrated the runtime to distroless. Please let me know if you think it shouldn't be closed.

**Pull request closed without merging**
